### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by Allamaris0** [ashishagarwal2023/freegpt#1]
I found my accesstoken

```
from freegpt.api.gpt import Bot
  
  token="mytoken"
  
  bot = Bot(token)
  print(bot.prompt("Hello. How are you"))
  bot.reset()
```

But I got error: 
```Traceback (most recent call last):
  File "C:\Users\Emilia\PycharmProjects\freegpt\freegpt\api\gpt.py", line 90, in prompt
    self.conversation_id = data["conversation_id"]
KeyError: 'conversation_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Emilia\PycharmProjects\freegpt\freechat.py", line 6, in <module>
    print(bot.prompt("Hello. How are you"))
  File "C:\Users\Emilia\PycharmProjects\freegpt\freegpt\api\gpt.py", line 92, in prompt
    raise TokenRateLimitedError("The token is rate limited. Try again later. From line 74", data)
freegpt.api.gpt.TokenRateLimitedError: The token is rate limited. Try again later. From line 74
```

**Comment by devashish2024** [comment]
Is it a bot token? I likely forgot to specify,youneed a account token.

**Comment by devashish2024** [comment]
It still works for me, you need a bot token. To get it, go to https://chat.openai.com/api/auth/session
2. Then find the accessToken key
3. Copy its value
4. Use it!

You must be logged in at chat.openai.com first to get a token

**Comment by devashish2024** [comment]
These are self tokens, they would be rate limited but are completely free like no payments

**Comment by Allamaris0** [comment]
Yes, it's this token and doesn't work for me :disappointed: 
@Edit
I tried with my second account and it works for it.

**Comment by devashish2024** [comment]
Are you rate limited? If the second account works and your main doesn't, its your issue.
I do not disable any tokens if you think.

**Comment by Allamaris0** [comment]
It doesn't work again for both accounts :|

**Comment by devashish2024** [comment]
Are you trying to spam? Give me your code (not token) and let me check. Are you rate limited? Is it the valid token? Use bot.verify(token) to test it.

**Comment by Allamaris0** [comment]
verify method returns {}
Both accounts are old (more than one year) and I can use it by browser. The code is like in the first post, just simple prompt.

**Comment by devashish2024** [comment]
Code

**Comment by devashish2024** [comment]
You can make a new account to test it.
Is your account like paid? Switch to free cuz paid=more  rate limits (and limited msgs)

**Comment by Allamaris0** [comment]
It works again with the same token 😵 My accounts are free. But how is it possible that my accounts are limited if I rarely use them?
Is that model` "model": "text-davinci-002-render-sha" `can be changed?

**Comment by devashish2024** [comment]
I do not know, are you leaking your tokens? :skull: Or do you chat lot on chat.openai.com?

I willl look tommorow if OpenAI is changing it

**Comment by vortexprime24** [comment]
Nope, cannot be changed.

I'm closing this feel free to re-open it if you have any queries. Have a try at <freegpt.js.org>, its stable.
